---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "master"
    schedule:
      interval: daily
    labels: ["dependencies", "backport release-24.11"]
    commit-message:
      prefix: "ci"
