{ colors }:
with colors;
{
  stylix.targets.blender.themeBody = ''
    <Theme>
      <user_interface>
        <ThemeUserInterface
          menu_shadow_fac="0.418571"
          menu_shadow_width="4"
          icon_alpha="1"
          icon_saturation="0.5"
          widget_emboss="#${base00-hex}05"
          editor_border="#${base00-hex}"
          editor_outline="#${base01-hex}"
          widget_text_cursor="#${base03-hex}"
          panel_roundness="0.4"
          transparent_checker_primary="#${base03-hex}"
          transparent_checker_secondary="#${base02-hex}"
          transparent_checker_size="8"
          axis_x="#${base08-hex}"
          axis_y="#${base07-hex}"
          axis_z="#${base09-hex}"
          gizmo_hi="#${base00-hex}"
          gizmo_primary="#${base00-hex}"
          gizmo_secondary="#${base00-hex}"
          gizmo_view_align="#${base07-hex}"
          gizmo_a="#${base00-hex}"
          gizmo_b="#${base00-hex}"
          icon_scene="#${base07-hex}ff"
          icon_collection="#${base07-hex}ff"
          icon_object="#${base07-hex}ff"
          icon_object_data="#${base07-hex}ff"
          icon_modifier="#${base07-hex}ff"
          icon_shading="#${base07-hex}ff"
          icon_folder="#${base07-hex}ff"
          icon_border_intensity="0.259259"
        >
          <wcol_regular>
            <ThemeWidgetColors
              outline="#${base01-hex}ff"
              inner="#${base01-hex}ff"
              inner_sel="#${base03-hex}a1"
              item="#${base04-hex}ff"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="0"
              shadedown="-5"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_regular>
          <wcol_tool>
            <ThemeWidgetColors
              outline="#${base02-hex}ff"
              inner="#${base02-hex}ff"
              inner_sel="#${base03-hex}ff"
              item="#${base07-hex}ff"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="0"
              shadedown="-5"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_tool>
          <wcol_toolbar_item>
            <ThemeWidgetColors
              outline="#${base02-hex}ff"
              inner="#${base02-hex}ff"
              inner_sel="#${base02-hex}ff"
              item="#${base07-hex}67"
              text="#${base07-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="0"
              shadedown="0"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_toolbar_item>
          <wcol_radio>
            <ThemeWidgetColors
              outline="#${base03-hex}ff"
              inner="#${base03-hex}ff"
              inner_sel="#${base02-hex}ff"
              item="#${base07-hex}ff"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="5"
              shadedown="-5"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_radio>
          <wcol_text>
            <ThemeWidgetColors
              outline="#${base01-hex}ff"
              inner="#${base01-hex}ff"
              inner_sel="#${base03-hex}ff"
              item="#${base04-hex}ff"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="TRUE"
              shadetop="-3"
              shadedown="0"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_text>
          <wcol_option>
            <ThemeWidgetColors
              outline="#${base03-hex}ff"
              inner="#${base03-hex}ff"
              inner_sel="#${base06-hex}ff"
              item="#${base07-hex}00"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="-14"
              shadedown="0"
              roundness="1"
            ></ThemeWidgetColors>
          </wcol_option>
          <wcol_toggle>
            <ThemeWidgetColors
              outline="#${base03-hex}ff"
              inner="#${base03-hex}ff"
              inner_sel="#${base03-hex}ff"
              item="#${base01-hex}ff"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="6"
              shadedown="0"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_toggle>
          <wcol_num>
            <ThemeWidgetColors
              outline="#${base01-hex}ff"
              inner="#${base01-hex}ff"
              inner_sel="#${base05-hex}50"
              item="#${base04-hex}ff"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="0"
              shadedown="0"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_num>
          <wcol_numslider>
            <ThemeWidgetColors
              outline="#${base01-hex}ff"
              inner="#${base01-hex}ff"
              inner_sel="#${base03-hex}ff"
              item="#${base04-hex}8c"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="-4"
              shadedown="0"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_numslider>
          <wcol_box>
            <ThemeWidgetColors
              outline="#${base01-hex}ff"
              inner="#${base01-hex}d9"
              inner_sel="#${base03-hex}ff"
              item="#${base01-hex}ff"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="0"
              shadedown="0"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_box>
          <wcol_menu>
            <ThemeWidgetColors
              outline="#${base01-hex}ff"
              inner="#${base01-hex}ff"
              inner_sel="#${base03-hex}ff"
              item="#${base05-hex}ff"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="10"
              shadedown="-10"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_menu>
          <wcol_pulldown>
            <ThemeWidgetColors
              outline="#${base03-hex}00"
              inner="#${base02-hex}99"
              inner_sel="#${base03-hex}7f"
              item="#${base04-hex}ff"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="25"
              shadedown="-20"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_pulldown>
          <wcol_menu_back>
            <ThemeWidgetColors
              outline="#${base01-hex}ff"
              inner="#${base01-hex}ef"
              inner_sel="#${base03-hex}ff"
              item="#${base04-hex}ff"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="25"
              shadedown="-20"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_menu_back>
          <wcol_pie_menu>
            <ThemeWidgetColors
              outline="#${base01-hex}ff"
              inner="#${base01-hex}d9"
              inner_sel="#${base03-hex}ff"
              item="#${base04-hex}ff"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="10"
              shadedown="-10"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_pie_menu>
          <wcol_tooltip>
            <ThemeWidgetColors
              outline="#${base01-hex}ff"
              inner="#${base01-hex}ef"
              inner_sel="#${base01-hex}ef"
              item="#${base01-hex}ef"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="25"
              shadedown="-20"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_tooltip>
          <wcol_menu_item>
            <ThemeWidgetColors
              outline="#${base01-hex}00"
              inner="#${base00-hex}00"
              inner_sel="#${base03-hex}cf"
              item="#${base07-hex}8f"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="38"
              shadedown="0"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_menu_item>
          <wcol_scroll>
            <ThemeWidgetColors
              outline="#${base01-hex}ff"
              inner="#${base0B-hex}5c"
              inner_sel="#${base03-hex}ff"
              item="#${base04-hex}ff"
              text="#${base07-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="5"
              shadedown="-5"
              roundness="1"
            ></ThemeWidgetColors>
          </wcol_scroll>
          <wcol_progress>
            <ThemeWidgetColors
              outline="#${base03-hex}ff"
              inner="#${base02-hex}ff"
              inner_sel="#${base03-hex}0f"
              item="#${base04-hex}0f"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="0"
              shadedown="0"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_progress>
          <wcol_list_item>
            <ThemeWidgetColors
              outline="#${base02-hex}ff"
              inner="#${base02-hex}00"
              inner_sel="#${base03-hex}ff"
              item="#${base05-hex}ff"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="0"
              shadedown="0"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_list_item>
          <wcol_state>
            <ThemeWidgetStateColors
              inner_anim="#${base0B-hex}"
              inner_anim_sel="#${base0C-hex}"
              inner_key="#${base03-hex}"
              inner_key_sel="#${base03-hex}"
              inner_driven="#${base03-hex}"
              inner_driven_sel="#${base03-hex}"
              inner_overridden="#${base0C-hex}"
              inner_overridden_sel="#${base0C-hex}"
              inner_changed="#${base09-hex}"
              inner_changed_sel="#${base09-hex}"
              blend="0.452381"
            ></ThemeWidgetStateColors>
          </wcol_state>
          <wcol_tab>
            <ThemeWidgetColors
              outline="#${base02-hex}ff"
              inner="#${base01-hex}ff"
              inner_sel="#${base03-hex}ff"
              item="#${base02-hex}ff"
              text="#${base05-hex}"
              text_sel="#${base06-hex}"
              show_shaded="FALSE"
              shadetop="0"
              shadedown="0"
              roundness="0.4"
            ></ThemeWidgetColors>
          </wcol_tab>
        </ThemeUserInterface>
      </user_interface>
      <view_3d>
        <ThemeView3D
          grid="#${base01-hex}3d"
          clipping_border_3d="#${base03-hex}ff"
          wire="#${base00-hex}"
          wire_edit="#${base01-hex}"
          edge_width="1"
          gp_vertex="#${base00-hex}"
          gp_vertex_select="#${base09-hex}"
          gp_vertex_size="3"
          text_grease_pencil="#${base0B-hex}"
          object_selected="#${base0B-hex}"
          object_active="#${base08-hex}"
          text_keyframe="#${base0A-hex}"
          camera="#${base00-hex}"
          empty="#${base00-hex}"
          light="#${base00-hex}28"
          speaker="#${base00-hex}"
          vertex="#${base00-hex}"
          vertex_select="#${base0B-hex}"
          vertex_active="#${base00-hex}"
          vertex_size="3"
          vertex_bevel="#${base0D-hex}"
          vertex_unreferenced="#${base00-hex}"
          edge_select="#${base03-hex}"
          edge_mode_select="#${base0C-hex}"
          edge_seam="#${base03-hex}"
          edge_sharp="#${base0C-hex}"
          edge_crease="#${base09-hex}"
          edge_bevel="#${base0D-hex}"
          edge_facesel="#${base03-hex}"
          freestyle_edge_mark="#${base0B-hex}"
          face="#${base00-hex}08"
          face_select="#${base03-hex}41"
          face_mode_select="#${base03-hex}33"
          face_dot="#${base0B-hex}"
          facedot_size="2"
          freestyle_face_mark="#${base0B-hex}33"
          face_retopology="#${base0D-hex}0f"
          face_back="#${base08-hex}b3"
          face_front="#${base0D-hex}b3"
          nurb_uline="#${base0A-hex}"
          nurb_vline="#${base09-hex}"
          nurb_sel_uline="#${base0B-hex}"
          nurb_sel_vline="#${base08-hex}"
          act_spline="#${base03-hex}"
          handle_free="#${base00-hex}"
          handle_auto="#${base0A-hex}"
          handle_vect="#${base0B-hex}"
          handle_sel_vect="#${base0B-hex}"
          handle_align="#${base03-hex}"
          handle_sel_free="#${base00-hex}"
          handle_sel_auto="#${base0A-hex}"
          handle_sel_align="#${base03-hex}"
          lastsel_point="#${base07-hex}"
          extra_edge_len="#${base01-hex}"
          extra_edge_angle="#${base0A-hex}"
          extra_face_angle="#${base0D-hex}"
          extra_face_area="#${base0B-hex}"
          editmesh_active="#${base07-hex}80"
          normal="#${base0C-hex}"
          vertex_normal="#${base0D-hex}"
          split_normal="#${base03-hex}"
          bone_pose="#${base0B-hex}"
          bone_pose_active="#${base03-hex}"
          bone_solid="#${base03-hex}"
          bone_locked_weight="#${base08-hex}80"
          bundle_solid="#${base05-hex}"
          camera_path="#${base00-hex}"
          camera_passepartout="#${base00-hex}"
          skin_root="#${base08-hex}"
          view_overlay="#${base00-hex}"
          transform="#${base07-hex}"
          frame_current="#${base0B-hex}"
          paint_curve_handle="#${base0B-hex}7f"
          paint_curve_pivot="#${base08-hex}7f"
          outline_width="4"
          object_origin_size="6"
        >
          <space>
            <ThemeSpaceGradient
              title="#${base05-hex}"
              text="#${base05-hex}"
              text_hi="#${base06-hex}"
              header="#${base01-hex}00"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base02-hex}00"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base03-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base01-hex}ff"
              tab_outline="#${base03-hex}ff"
            >
              <gradients>
                <ThemeGradientColors
                  background_type="SINGLE_COLOR"
                  high_gradient="#${base01-hex}"
                  gradient="#${base01-hex}"
                ></ThemeGradientColors>
              </gradients>
              <panelcolors>
                <ThemePanelColors
                  header="#${base02-hex}cc"
                  back="#${base01-hex}cc"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGradient>
          </space>
          <asset_shelf>
            <ThemeAssetShelf
              header_back="#${base01-hex}ff"
              back="#${base02-hex}ff"
            ></ThemeAssetShelf>
          </asset_shelf>
        </ThemeView3D>
      </view_3d>
      <graph_editor>
        <ThemeGraphEditor
          grid="#${base01-hex}"
          frame_current="#${base03-hex}"
          time_scrub_background="#${base02-hex}e6"
          time_marker_line="#${base00-hex}60"
          time_marker_line_selected="#${base07-hex}60"
          window_sliders="#${base05-hex}"
          channels_region="#${base01-hex}"
          dopesheet_channel="#${base03-hex}"
          dopesheet_subchannel="#${base03-hex}"
          channel_group="#${base01-hex}"
          active_channels_group="#${base03-hex}"
          preview_range="#${base09-hex}66"
          vertex="#${base05-hex}"
          vertex_select="#${base09-hex}"
          vertex_active="#${base07-hex}"
          vertex_size="6"
          vertex_bevel="#${base00-hex}"
          vertex_unreferenced="#${base00-hex}"
          handle_free="#${base00-hex}"
          handle_auto="#${base0A-hex}"
          handle_vect="#${base0B-hex}"
          handle_sel_vect="#${base0B-hex}"
          handle_align="#${base09-hex}"
          handle_sel_free="#${base00-hex}"
          handle_sel_auto="#${base0A-hex}"
          handle_sel_align="#${base03-hex}"
          handle_auto_clamped="#${base03-hex}"
          handle_sel_auto_clamped="#${base03-hex}"
          lastsel_point="#${base07-hex}"
          handle_vertex="#${base03-hex}"
          handle_vertex_select="#${base0C-hex}"
          handle_vertex_size="5"
        >
          <space>
            <ThemeSpaceGeneric
              back="#${base01-hex}"
              title="#${base07-hex}"
              text="#${base05-hex}"
              text_hi="#${base07-hex}"
              header="#${base02-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base01-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base08-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base01-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base02-hex}ff"
                  back="#${base02-hex}ff"
                  sub_back="#${base00-hex}1f"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
          <space_list>
            <ThemeSpaceListGeneric
              list="#${base01-hex}"
              list_title="#${base07-hex}"
              list_text="#${base05-hex}"
              list_text_hi="#${base07-hex}"
            ></ThemeSpaceListGeneric>
          </space_list>
        </ThemeGraphEditor>
      </graph_editor>
      <file_browser>
        <ThemeFileBrowser
          selected_file="#${base03-hex}"
          row_alternate="#${base07-hex}07"
        >
          <space>
            <ThemeSpaceGeneric
              back="#${base01-hex}"
              title="#${base07-hex}"
              text="#${base05-hex}"
              text_hi="#${base07-hex}"
              header="#${base01-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base02-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base03-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base02-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base02-hex}ff"
                  back="#${base01-hex}b3"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
        </ThemeFileBrowser>
      </file_browser>
      <nla_editor>
        <ThemeNLAEditor
          grid="#${base03-hex}"
          view_sliders="#${base05-hex}"
          dopesheet_channel="#${base0C-hex}"
          dopesheet_subchannel="#${base0D-hex}"
          nla_track="#${base03-hex}"
          active_action="#${base03-hex}4d"
          active_action_unset="#${base03-hex}4d"
          preview_range="#${base09-hex}66"
          strips="#${base0D-hex}"
          strips_selected="#${base03-hex}"
          transition_strips="#${base01-hex}"
          transition_strips_selected="#${base0D-hex}"
          meta_strips="#${base02-hex}"
          meta_strips_selected="#${base03-hex}"
          sound_strips="#${base02-hex}"
          sound_strips_selected="#${base0C-hex}"
          tweak="#${base0B-hex}"
          tweak_duplicate="#${base08-hex}"
          keyframe_border="#${base00-hex}ff"
          keyframe_border_selected="#${base00-hex}ff"
          frame_current="#${base03-hex}"
          time_scrub_background="#${base02-hex}e6"
          time_marker_line="#${base00-hex}60"
          time_marker_line_selected="#${base07-hex}60"
        >
          <space>
            <ThemeSpaceGeneric
              back="#${base01-hex}"
              title="#${base07-hex}"
              text="#${base07-hex}"
              text_hi="#${base07-hex}"
              header="#${base02-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base01-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base08-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base02-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base01-hex}cc"
                  back="#${base02-hex}b3"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
          <space_list>
            <ThemeSpaceListGeneric
              list="#${base02-hex}"
              list_title="#${base07-hex}"
              list_text="#${base05-hex}"
              list_text_hi="#${base05-hex}"
            ></ThemeSpaceListGeneric>
          </space_list>
        </ThemeNLAEditor>
      </nla_editor>
      <dopesheet_editor>
        <ThemeDopeSheet
          grid="#${base02-hex}"
          frame_current="#${base03-hex}"
          time_scrub_background="#${base02-hex}e6"
          time_marker_line="#${base00-hex}60"
          time_marker_line_selected="#${base07-hex}60"
          value_sliders="#${base00-hex}"
          view_sliders="#${base05-hex}"
          dopesheet_channel="#${base03-hex}ff"
          dopesheet_subchannel="#${base03-hex}16"
          channels="#${base01-hex}58"
          channels_selected="#${base03-hex}85"
          channel_group="#${base01-hex}50"
          active_channels_group="#${base0B-hex}55"
          long_key="#${base01-hex}80"
          long_key_selected="#${base03-hex}cc"
          keyframe="#${base05-hex}"
          keyframe_selected="#${base03-hex}"
          keyframe_extreme="#${base03-hex}"
          keyframe_extreme_selected="#${base08-hex}"
          keyframe_breakdown="#${base0D-hex}"
          keyframe_breakdown_selected="#${base0D-hex}"
          keyframe_jitter="#${base0B-hex}"
          keyframe_jitter_selected="#${base0B-hex}"
          keyframe_movehold="#${base03-hex}"
          keyframe_movehold_selected="#${base0A-hex}"
          keyframe_border="#${base00-hex}ff"
          keyframe_border_selected="#${base0B-hex}ff"
          keyframe_scale_factor="1"
          summary="#${base01-hex}ff"
          preview_range="#${base09-hex}66"
          interpolation_line="#${base0B-hex}cc"
          simulated_frames="#${base03-hex}ff"
        >
          <space>
            <ThemeSpaceGeneric
              back="#${base01-hex}"
              title="#${base05-hex}"
              text="#${base05-hex}"
              text_hi="#${base05-hex}"
              header="#${base02-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base01-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base08-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base02-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base01-hex}cc"
                  back="#${base02-hex}a1"
                  sub_back="#${base00-hex}46"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
          <space_list>
            <ThemeSpaceListGeneric
              list="#${base01-hex}"
              list_title="#${base05-hex}"
              list_text="#${base05-hex}"
              list_text_hi="#${base07-hex}"
            ></ThemeSpaceListGeneric>
          </space_list>
        </ThemeDopeSheet>
      </dopesheet_editor>
      <image_editor>
        <ThemeImageEditor
          grid="#${base02-hex}ff"
          vertex="#${base00-hex}"
          vertex_select="#${base0C-hex}"
          vertex_active="#${base03-hex}"
          vertex_size="3"
          vertex_bevel="#${base00-hex}"
          vertex_unreferenced="#${base00-hex}"
          face="#${base07-hex}0a"
          face_select="#${base0C-hex}45"
          face_mode_select="#${base00-hex}00"
          face_dot="#${base0B-hex}"
          facedot_size="3"
          freestyle_face_mark="#${base0B-hex}33"
          face_retopology="#${base00-hex}00"
          face_back="#${base00-hex}00"
          face_front="#${base00-hex}00"
          editmesh_active="#${base07-hex}80"
          wire_edit="#${base05-hex}"
          edge_width="1"
          edge_select="#${base0C-hex}"
          scope_back="#${base03-hex}ff"
          preview_stitch_face="#${base0A-hex}33"
          preview_stitch_edge="#${base03-hex}33"
          preview_stitch_vert="#${base0D-hex}33"
          preview_stitch_stitchable="#${base0B-hex}ff"
          preview_stitch_unstitchable="#${base08-hex}ff"
          preview_stitch_active="#${base05-hex}23"
          uv_shadow="#${base03-hex}ff"
          frame_current="#${base0B-hex}"
          metadatabg="#${base00-hex}"
          metadatatext="#${base07-hex}"
          handle_free="#${base00-hex}"
          handle_auto="#${base0A-hex}"
          handle_align="#${base03-hex}"
          handle_sel_free="#${base00-hex}"
          handle_sel_auto="#${base0A-hex}"
          handle_sel_align="#${base09-hex}"
          handle_auto_clamped="#${base00-hex}"
          handle_sel_auto_clamped="#${base00-hex}"
          handle_vertex="#${base00-hex}"
          handle_vertex_select="#${base0A-hex}"
          handle_vertex_size="5"
          paint_curve_handle="#${base0B-hex}7f"
          paint_curve_pivot="#${base08-hex}7f"
        >
          <space>
            <ThemeSpaceGeneric
              back="#${base01-hex}"
              title="#${base05-hex}"
              text="#${base07-hex}"
              text_hi="#${base07-hex}"
              header="#${base01-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base01-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base0B-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base02-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base01-hex}cc"
                  back="#${base02-hex}b3"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
        </ThemeImageEditor>
      </image_editor>
      <sequence_editor>
        <ThemeSequenceEditor
          grid="#${base03-hex}"
          window_sliders="#${base05-hex}"
          movie_strip="#${base0D-hex}"
          movieclip_strip="#${base0D-hex}"
          image_strip="#${base03-hex}"
          scene_strip="#${base0B-hex}"
          audio_strip="#${base0C-hex}"
          effect_strip="#${base09-hex}"
          transition_strip="#${base03-hex}"
          color_strip="#${base03-hex}"
          meta_strip="#${base0C-hex}"
          mask_strip="#${base03-hex}"
          text_strip="#${base0A-hex}"
          active_strip="#${base05-hex}"
          selected_strip="#${base09-hex}"
          frame_current="#${base03-hex}"
          time_scrub_background="#${base02-hex}e6"
          time_marker_line="#${base00-hex}60"
          time_marker_line_selected="#${base07-hex}60"
          keyframe="#${base09-hex}"
          keyframe_selected="#${base0A-hex}"
          keyframe_breakdown="#${base0D-hex}"
          keyframe_breakdown_selected="#${base0D-hex}"
          keyframe_movehold="#${base03-hex}"
          keyframe_movehold_selected="#${base0A-hex}"
          keyframe_border="#${base00-hex}ff"
          keyframe_border_selected="#${base00-hex}ff"
          draw_action="#${base0D-hex}"
          preview_back="#${base00-hex}"
          metadatabg="#${base00-hex}"
          metadatatext="#${base07-hex}"
          preview_range="#${base09-hex}66"
          row_alternate="#${base07-hex}0d"
        >
          <space>
            <ThemeSpaceGeneric
              back="#${base01-hex}"
              title="#${base05-hex}"
              text="#${base05-hex}"
              text_hi="#${base07-hex}"
              header="#${base01-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base01-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base08-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base02-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base01-hex}cc"
                  back="#${base02-hex}b3"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
          <space_list>
            <ThemeSpaceListGeneric
              list="#${base01-hex}"
              list_title="#${base07-hex}"
              list_text="#${base07-hex}"
              list_text_hi="#${base07-hex}"
            ></ThemeSpaceListGeneric>
          </space_list>
        </ThemeSequenceEditor>
      </sequence_editor>
      <properties>
        <ThemeProperties
          match="#${base0D-hex}"
          active_modifier="#${base0D-hex}ff"
        >
          <space>
            <ThemeSpaceGeneric
              back="#${base01-hex}"
              title="#${base05-hex}"
              text="#${base05-hex}"
              text_hi="#${base07-hex}"
              header="#${base01-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base01-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base02-hex}ff"
              execution_buts="#${base00-hex}00"
              tab_active="#${base08-hex}"
              tab_inactive="#${base02-hex}"
              tab_back="#${base01-hex}ff"
              tab_outline="#${base01-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base0B-hex}00"
                  back="#${base00-hex}28"
                  sub_back="#${base00-hex}24"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
        </ThemeProperties>
      </properties>
      <text_editor>
        <ThemeTextEditor
          line_numbers="#${base05-hex}"
          line_numbers_background="#${base02-hex}"
          selected_text="#${base01-hex}"
          cursor="#${base0B-hex}"
          syntax_builtin="#${base08-hex}"
          syntax_symbols="#${base0D-hex}"
          syntax_special="#${base0D-hex}"
          syntax_preprocessor="#${base03-hex}"
          syntax_reserved="#${base09-hex}"
          syntax_comment="#${base03-hex}"
          syntax_string="#${base0A-hex}"
          syntax_numbers="#${base0C-hex}"
        >
          <space>
            <ThemeSpaceGeneric
              back="#${base02-hex}"
              title="#${base05-hex}"
              text="#${base05-hex}"
              text_hi="#${base07-hex}"
              header="#${base01-hex}00"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base01-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base08-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base02-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base01-hex}00"
                  back="#${base01-hex}b3"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
        </ThemeTextEditor>
      </text_editor>
      <node_editor>
        <ThemeNodeEditor
          grid="#${base02-hex}"
          node_selected="#${base0C-hex}"
          node_active="#${base03-hex}"
          wire="#${base05-hex}ff"
          wire_inner="#${base05-hex}"
          wire_select="#${base03-hex}b3"
          selected_text="#${base03-hex}"
          node_backdrop="#${base02-hex}ff"
          converter_node="#${base0D-hex}"
          color_node="#${base0A-hex}"
          group_node="#${base0C-hex}"
          group_socket_node="#${base01-hex}"
          frame_node="#${base05-hex}a0"
          matte_node="#${base09-hex}"
          distor_node="#${base03-hex}"
          noodle_curving="4"
          grid_levels="1"
          dash_alpha="0.5"
          input_node="#${base08-hex}"
          output_node="#${base0C-hex}"
          filter_node="#${base03-hex}"
          vector_node="#${base03-hex}"
          texture_node="#${base09-hex}"
          shader_node="#${base03-hex}"
          script_node="#${base0C-hex}"
          pattern_node="#${base03-hex}"
          layout_node="#${base03-hex}"
          geometry_node="#${base0C-hex}"
          attribute_node="#${base0D-hex}"
          simulation_zone="#${base03-hex}33"
          repeat_zone="#${base09-hex}33"
        >
          <space>
            <ThemeSpaceGeneric
              back="#${base01-hex}"
              title="#${base05-hex}"
              text="#${base05-hex}"
              text_hi="#${base07-hex}"
              header="#${base01-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base02-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base03-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base01-hex}ff"
              tab_outline="#${base03-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base01-hex}cc"
                  back="#${base01-hex}00"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
          <space_list>
            <ThemeSpaceListGeneric
              list="#${base02-hex}"
              list_title="#${base07-hex}"
              list_text="#${base05-hex}"
              list_text_hi="#${base07-hex}"
            ></ThemeSpaceListGeneric>
          </space_list>
        </ThemeNodeEditor>
      </node_editor>
      <outliner>
        <ThemeOutliner
          match="#${base0D-hex}"
          selected_highlight="#${base03-hex}"
          active="#${base03-hex}"
          selected_object="#${base08-hex}"
          active_object="#${base07-hex}"
          edited_object="#${base0B-hex}66"
          row_alternate="#${base07-hex}07"
        >
          <space>
            <ThemeSpaceGeneric
              back="#${base01-hex}"
              title="#${base07-hex}"
              text="#${base05-hex}"
              text_hi="#${base07-hex}"
              header="#${base01-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base01-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base03-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base02-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base01-hex}cc"
                  back="#${base02-hex}b3"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
        </ThemeOutliner>
      </outliner>
      <info>
        <ThemeInfo
          info_selected="#${base0D-hex}"
          info_selected_text="#${base07-hex}"
          info_error="#${base08-hex}ff"
          info_error_text="#${base07-hex}"
          info_warning="#${base09-hex}ff"
          info_warning_text="#${base07-hex}"
          info_info="#${base0B-hex}ff"
          info_info_text="#${base07-hex}"
          info_debug="#${base05-hex}ff"
          info_debug_text="#${base00-hex}"
          info_property="#${base0B-hex}ff"
          info_property_text="#${base07-hex}"
          info_operator="#${base0B-hex}ff"
          info_operator_text="#${base07-hex}"
        >
          <space>
            <ThemeSpaceGeneric
              back="#${base01-hex}"
              title="#${base05-hex}"
              text="#${base07-hex}"
              text_hi="#${base07-hex}"
              header="#${base01-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base01-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base08-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base02-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base01-hex}cc"
                  back="#${base02-hex}b3"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
        </ThemeInfo>
      </info>
      <preferences>
        <ThemePreferences>
          <space>
            <ThemeSpaceGeneric
              back="#${base01-hex}"
              title="#${base05-hex}"
              text="#${base05-hex}"
              text_hi="#${base07-hex}"
              header="#${base02-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base02-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base02-hex}ff"
              execution_buts="#${base02-hex}ff"
              tab_active="#${base03-hex}"
              tab_inactive="#${base02-hex}"
              tab_back="#${base02-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base02-hex}00"
                  back="#${base02-hex}b3"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
        </ThemePreferences>
      </preferences>
      <console>
        <ThemeConsole
          line_output="#${base03-hex}"
          line_input="#${base07-hex}"
          line_info="#${base0B-hex}"
          line_error="#${base08-hex}"
          cursor="#${base0B-hex}"
          select="#${base07-hex}30"
        >
          <space>
            <ThemeSpaceGeneric
              back="#${base00-hex}"
              title="#${base05-hex}"
              text="#${base07-hex}"
              text_hi="#${base07-hex}"
              header="#${base01-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base01-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base08-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base02-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base01-hex}cc"
                  back="#${base02-hex}b3"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
        </ThemeConsole>
      </console>
      <clip_editor>
        <ThemeClipEditor
          grid="#${base02-hex}ff"
          marker_outline="#${base00-hex}"
          marker="#${base03-hex}"
          active_marker="#${base07-hex}"
          selected_marker="#${base0A-hex}"
          disabled_marker="#${base08-hex}"
          locked_marker="#${base03-hex}"
          path_before="#${base08-hex}"
          path_after="#${base0D-hex}"
          path_keyframe_before="#${base08-hex}"
          path_keyframe_after="#${base0D-hex}"
          frame_current="#${base0B-hex}"
          time_scrub_background="#${base02-hex}e6"
          time_marker_line="#${base00-hex}60"
          time_marker_line_selected="#${base07-hex}60"
          strips="#${base00-hex}"
          strips_selected="#${base09-hex}"
          metadatabg="#${base00-hex}"
          metadatatext="#${base07-hex}"
          handle_free="#${base00-hex}"
          handle_auto="#${base03-hex}"
          handle_align="#${base03-hex}"
          handle_sel_free="#${base00-hex}"
          handle_sel_auto="#${base0A-hex}"
          handle_sel_align="#${base09-hex}"
          handle_auto_clamped="#${base00-hex}"
          handle_sel_auto_clamped="#${base00-hex}"
          handle_vertex="#${base00-hex}"
          handle_vertex_select="#${base0A-hex}"
          handle_vertex_size="5"
        >
          <space>
            <ThemeSpaceGeneric
              back="#${base01-hex}"
              title="#${base05-hex}"
              text="#${base07-hex}"
              text_hi="#${base07-hex}"
              header="#${base01-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base01-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base08-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base02-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base01-hex}cc"
                  back="#${base02-hex}b3"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
          <space_list>
            <ThemeSpaceListGeneric
              list="#${base03-hex}"
              list_title="#${base00-hex}"
              list_text="#${base00-hex}"
              list_text_hi="#${base07-hex}"
            ></ThemeSpaceListGeneric>
          </space_list>
        </ThemeClipEditor>
      </clip_editor>
      <topbar>
        <ThemeTopBar>
          <space>
            <ThemeSpaceGeneric
              back="#${base02-hex}"
              title="#${base07-hex}"
              text="#${base07-hex}"
              text_hi="#${base07-hex}"
              header="#${base02-hex}ff"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base01-hex}ff"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base08-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base02-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base01-hex}cc"
                  back="#${base02-hex}b3"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
        </ThemeTopBar>
      </topbar>
      <statusbar>
        <ThemeStatusBar>
          <space>
            <ThemeSpaceGeneric
              back="#${base02-hex}"
              title="#${base07-hex}"
              text="#${base03-hex}"
              text_hi="#${base07-hex}"
              header="#${base01-hex}ff"
              header_text="#${base03-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base02-hex}ff"
              button_title="#${base00-hex}"
              button_text="#${base00-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base00-hex}00"
              execution_buts="#${base00-hex}00"
              tab_active="#${base08-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base02-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base01-hex}cc"
                  back="#${base02-hex}b3"
                  sub_back="#${base00-hex}3e"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
        </ThemeStatusBar>
      </statusbar>
      <spreadsheet>
        <ThemeSpreadsheet row_alternate="#${base07-hex}04">
          <space>
            <ThemeSpaceGeneric
              back="#${base02-hex}"
              title="#${base07-hex}"
              text="#${base05-hex}"
              text_hi="#${base07-hex}"
              header="#${base02-hex}b3"
              header_text="#${base05-hex}"
              header_text_hi="#${base07-hex}"
              button="#${base02-hex}00"
              button_title="#${base07-hex}"
              button_text="#${base05-hex}"
              button_text_hi="#${base07-hex}"
              navigation_bar="#${base01-hex}ff"
              execution_buts="#${base02-hex}ff"
              tab_active="#${base02-hex}"
              tab_inactive="#${base01-hex}"
              tab_back="#${base01-hex}ff"
              tab_outline="#${base02-hex}ff"
            >
              <panelcolors>
                <ThemePanelColors
                  header="#${base02-hex}ff"
                  back="#${base02-hex}ff"
                  sub_back="#${base00-hex}1f"
                ></ThemePanelColors>
              </panelcolors>
            </ThemeSpaceGeneric>
          </space>
          <space_list>
            <ThemeSpaceListGeneric
              list="#${base02-hex}"
              list_title="#${base05-hex}"
              list_text="#${base05-hex}"
              list_text_hi="#${base09-hex}"
            ></ThemeSpaceListGeneric>
          </space_list>
        </ThemeSpreadsheet>
      </spreadsheet>
      <bone_color_sets>
        <ThemeBoneColorSet
          normal="#${base08-hex}"
          select="#${base08-hex}"
          active="#${base08-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base09-hex}"
          select="#${base09-hex}"
          active="#${base09-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base0B-hex}"
          select="#${base0B-hex}"
          active="#${base0B-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base0D-hex}"
          select="#${base0D-hex}"
          active="#${base0D-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base03-hex}"
          select="#${base03-hex}"
          active="#${base03-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base03-hex}"
          select="#${base03-hex}"
          active="#${base03-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base0B-hex}"
          select="#${base0B-hex}"
          active="#${base0B-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base0C-hex}"
          select="#${base0C-hex}"
          active="#${base0C-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base0A-hex}"
          select="#${base0A-hex}"
          active="#${base0A-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base01-hex}"
          select="#${base02-hex}"
          active="#${base07-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base03-hex}"
          select="#${base03-hex}"
          active="#${base03-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base0B-hex}"
          select="#${base0B-hex}"
          active="#${base0B-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base03-hex}"
          select="#${base03-hex}"
          active="#${base05-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base09-hex}"
          select="#${base09-hex}"
          active="#${base09-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base0B-hex}"
          select="#${base0B-hex}"
          active="#${base0B-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base00-hex}"
          select="#${base00-hex}"
          active="#${base00-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base00-hex}"
          select="#${base00-hex}"
          active="#${base00-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base00-hex}"
          select="#${base00-hex}"
          active="#${base00-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base00-hex}"
          select="#${base00-hex}"
          active="#${base00-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
        <ThemeBoneColorSet
          normal="#${base00-hex}"
          select="#${base00-hex}"
          active="#${base00-hex}"
          show_colored_constraints="FALSE"
        ></ThemeBoneColorSet>
      </bone_color_sets>
      <collection_color>
        <ThemeCollectionColor color="#${base03-hex}"></ThemeCollectionColor>
        <ThemeCollectionColor color="#${base0B-hex}"></ThemeCollectionColor>
        <ThemeCollectionColor color="#${base0D-hex}"></ThemeCollectionColor>
        <ThemeCollectionColor color="#${base0C-hex}"></ThemeCollectionColor>
        <ThemeCollectionColor color="#${base03-hex}"></ThemeCollectionColor>
        <ThemeCollectionColor color="#${base0D-hex}"></ThemeCollectionColor>
        <ThemeCollectionColor color="#${base05-hex}"></ThemeCollectionColor>
        <ThemeCollectionColor color="#${base0B-hex}"></ThemeCollectionColor>
      </collection_color>
      <strip_color>
        <ThemeStripColor color="#${base08-hex}"></ThemeStripColor>
        <ThemeStripColor color="#${base09-hex}"></ThemeStripColor>
        <ThemeStripColor color="#${base0A-hex}"></ThemeStripColor>
        <ThemeStripColor color="#${base0B-hex}"></ThemeStripColor>
        <ThemeStripColor color="#${base0C-hex}"></ThemeStripColor>
        <ThemeStripColor color="#${base0D-hex}"></ThemeStripColor>
        <ThemeStripColor color="#${base03-hex}"></ThemeStripColor>
        <ThemeStripColor color="#${base03-hex}"></ThemeStripColor>
        <ThemeStripColor color="#${base03-hex}"></ThemeStripColor>
      </strip_color>
    </Theme>
  '';
}
