---
description: Request a change to an existing option
labels: [change-option]
name: Change option
title: "<SCOPE>: <DESCRIPTION>"

body:
  - type: checkboxes

    attributes:
      label: I assert that this feature request is relevant for Stylix

      options:
        - label: >-
            I assert that this is not a duplicate of an [existing feature
            request](https://github.com/danth/stylix/issues).

          required: true

  - type: textarea

    attributes:
      label: Description

      description: >-
        Describe the change and its potential breaking changes, and demonstrate
        the use case it improves.

      placeholder: Type your description here…

    validations:
      required: true

  - type: textarea

    attributes:
      label: Notify maintainers

      description: >-
        Notify the maintainers of the module that the target is under. You can
        find who maintains a module by referencing the
        [Stylix book](https://stylix.danth.me/) and navigating to the specific
        module on the sidebar under "Modules >".

      placeholder: "@danth, @trueNAHO"
