---
description: Change an existing target.
labels: [change-target]
name: Change target
title: "<TARGET>: <DESCRIPTION>"

body:
  - type: checkboxes

    attributes:
      label: I assert that this feature request is relevant for Stylix

      options:
        - label: >-
            I assert that this is not a duplicate of an [existing feature
            request](https://github.com/danth/stylix/labels/change-target).

          required: true

  - type: textarea

    attributes:
      label: Description
      description: >-
        Describe the change. Consider including links to preexisting NixOS,
        home-manager, and/or nix-darwin options which could be leveraged to
        make this change.

    validations:
      required: true
