---
blank_issues_enabled: true

contact_links:
  - name: Ask on GitHub Discussions
    url: https://github.com/danth/stylix/discussions/new/choose
    about: For questions or informal discussions

  - name: Ask on Matrix
    url: https://matrix.to/#/#stylix:danth.me
    about: For questions or informal discussions
