---
description: Request a feature.
labels: [feature]
name: Feature request
title: "<SCOPE>: <SUMMARY>"

body:
  - type: checkboxes

    attributes:
      label: Has this been requested before?
      description: >-
        Search [existing issues](https://github.com/danth/stylix/issues) to
        ensure that this feature hasn't been requested before.

    options:
      - label: >-
          I have searched for and not found existing issues requesting this
          feature
        required: true

  - type: dropdown

    attributes:
      label: Feature Type
      description: What kind of feature is this?

      options:
        - New target
        - Change to existing target
        - New Stylix option
        - Change to existing Stylix option
        - Other (describe below)

    validations:
      required: true

  - type: textarea

    attributes:
      label: Description
      description: >-
        Describe the feature. For new targets, consider including links to
        existing theme repositories for the target (e.g. a tinted-theming
        repository). For new options, consider including examples of ways the
        option would be used in existing targets.

    validations:
      required: true
