---
description: Request the addition of a new option
labels: [new-option]
name: New option
title: "<SCOPE>: add <OPTION> option"

body:
  - type: checkboxes

    attributes:
      label: I assert that this feature request is relevant for Stylix

      options:
        - label: >-
            I assert that this is not a duplicate of an [existing feature
            request](https://github.com/danth/stylix/issues).

          required: true

  - type: textarea

    attributes:
      label: Description

      description: >-
        Describe the option and explain its use case. Consider including
        pseudocode demonstrating its integration with the existing architecture.

      placeholder: Type your description here...

    validations:
      required: true

  - type: textarea

    attributes:
      label: Notify maintainers

      description: >-
        If this option would be specific to a module, notify the maintainers
        of that module. You can find who maintains a module by referencing the
        [Stylix book](https://stylix.danth.me/) and navigating to the specific
        module on the sidebar under "Modules >".

      placeholder: "@ the maintainers here..."
