---
description: Add a new target.
labels: [new-target]
name: New target
title: "<TARGET>: init"

body:
  - type: checkboxes

    attributes:
      label: I assert that this feature request is relevant for Stylix

    options:
      - label: >-
          I assert that this is not a duplicate of an [existing feature
          request](https://github.com/danth/stylix/labels/new-target).
        required: true

  - type: textarea

    attributes:
      label: Description
      description: >-
        Describe the feature. Consider including links to existing themes, like
        a [tinted-theming repository](https://github.com/tinted-theming).

    validations:
      required: true
