config: let
    polarity = config.stylix.polarity;
in ''
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<package format="1" xmlns="https://wiki.freecad.org/Package_Metadata">
  <name>Stylix</name>
  <description>Autogenerated Stylix ${polarity} theme for FreeCAD</description>
  <version>0.0.1</version>
  <license file="LICENSE">MIT</license>
  <url type="repository" branch="master">https://github.com/danth/stylix</url>

  <content>
    <preferencepack>
      <name>Stylix</name>
      <description>Autogenerated Stylix ${polarity} theme for FreeCAD</description>
      <tag>stylix</tag>
      <tag>${polarity}</tag>
      <tag>stylesheet</tag>
      <tag>theme</tag>
    </preferencepack>
  </content>

</package>
''
